/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as LocationAddress from "../../../community/lexicon/location/address.defs";
import * as LocationFsq from "../../../community/lexicon/location/fsq.defs";
import * as LocationGeo from "../../../community/lexicon/location/geo.defs";
import * as LocationHthree from "../../../community/lexicon/location/hthree.defs";
import * as LabelDefs from "../../../com/atproto/label/defs.defs";

const $nsid = "social.laundryroom.group.profile";

type $nsid = typeof $nsid;

export { $nsid };

/** A laundryroom group's profile, authored by the group's own DID. Always in the group's meta/self space; also in the group's public repo while the group is active, and only then. */
type Main = {
  $type: "social.laundryroom.group.profile";

  /**
   * The group's name. Same limit as group.opensocial.profile.
   */
  displayName: string;

  /**
   * What the group is about.
   */
  description?: string;

  /**
   * The group's image.
   */
  avatar?: l.BlobRef;

  /**
   * Alt text for the avatar.
   */
  avatarAlt?: string;

  /**
   * Where the group meets, as free text (for example a city or neighbourhood).
   */
  locationName?: string;

  /**
   * A structured location for the group, when one is known.
   */
  location?:
    | l.$Typed<LocationAddress.Main>
    | l.$Typed<LocationFsq.Main>
    | l.$Typed<LocationGeo.Main>
    | l.$Typed<LocationHthree.Main>
    | l.Unknown$TypedObject;

  /**
   * ISO 3166-1 alpha-2 country code of the group, for example DE. Used as the country of event addresses.
   */
  country?: string;

  /**
   * IANA time zone name the group's meetups are shown in, for example Europe/Berlin.
   */
  timeZone?: string;

  /**
   * Self-labels on the group, for example for adult content.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject;

  /**
   * Client-declared timestamp when the group was created. Kept on updates.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A laundryroom group's profile, authored by the group's own DID. Always in the group's meta/self space; also in the group's public repo while the group is active, and only then. */
const main = /*#__PURE__*/ l.record<"literal:self", Main>(
  "literal:self",
  $nsid,
  /*#__PURE__*/ l.object({
    displayName: /*#__PURE__*/ l.string({
      minGraphemes: 1,
      maxGraphemes: 64,
      maxLength: 640,
    }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 2000, maxLength: 20000 }),
    ),
    avatar: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({
        accept: ["image/png", "image/jpeg", "image/webp"],
        maxSize: 2000000,
      }),
    ),
    avatarAlt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 1000, maxLength: 10000 }),
    ),
    locationName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 255, maxLength: 2550 }),
    ),
    location: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<LocationAddress.Main>(
            (() => LocationAddress.main) as any,
          ),
          /*#__PURE__*/ l.typedRef<LocationFsq.Main>(
            (() => LocationFsq.main) as any,
          ),
          /*#__PURE__*/ l.typedRef<LocationGeo.Main>(
            (() => LocationGeo.main) as any,
          ),
          /*#__PURE__*/ l.typedRef<LocationHthree.Main>(
            (() => LocationHthree.main) as any,
          ),
        ],
        false,
      ),
    ),
    country: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ minLength: 2, maxLength: 2 }),
    ),
    timeZone: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 64 }),
    ),
    labels: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<LabelDefs.SelfLabels>(
            (() => LabelDefs.selfLabels) as any,
          ),
        ],
        false,
      ),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
