packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  "@trpc/client": next
  "@trpc/react-query": next
  "@trpc/server": next
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: beta
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
