/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as LocationAddress from "../location/address.defs";
import * as LocationFsq from "../location/fsq.defs";
import * as LocationGeo from "../location/geo.defs";
import * as LocationHthree from "../location/hthree.defs";

const $nsid = "community.lexicon.calendar.event";

type $nsid = typeof $nsid;

export { $nsid };

/** A URI associated with the event. */
type Uri = {
  $type?: "community.lexicon.calendar.event#uri";
  uri: l.UriString;

  /**
   * The display name of the URI.
   */
  name?: string;
};

export type { Uri };

/** A URI associated with the event. */
const uri = /*#__PURE__*/ l.typedObject<Uri>(
  $nsid,
  "uri",
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ format: "uri" }),
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
);

export { uri };

/** A calendar event. */
type Main = {
  $type: "community.lexicon.calendar.event";

  /**
   * The attendance mode of the event.
   */
  mode?: Mode;

  /**
   * The name of the event.
   */
  name: string;

  /**
   * URIs associated with the event.
   */
  uris?: Uri[];

  /**
   * Client-declared timestamp when the event ends.
   */
  endsAt?: l.DatetimeString;

  /**
   * The status of the event.
   */
  status?: Status;

  /**
   * Client-declared timestamp when the event starts.
   */
  startsAt?: l.DatetimeString;

  /**
   * Client-declared timestamp when the event was created.
   */
  createdAt: l.DatetimeString;

  /**
   * The locations where the event takes place.
   */
  locations?: (
    | l.$Typed<Uri>
    | l.$Typed<LocationAddress.Main>
    | l.$Typed<LocationFsq.Main>
    | l.$Typed<LocationGeo.Main>
    | l.$Typed<LocationHthree.Main>
    | l.Unknown$TypedObject
  )[];

  /**
   * The description of the event.
   */
  description?: string;
};

export type { Main };

/** A calendar event. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    mode: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Mode>((() => mode) as any),
    ),
    name: /*#__PURE__*/ l.string(),
    uris: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.ref<Uri>((() => uri) as any)),
    ),
    endsAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: "datetime" }),
    ),
    status: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Status>((() => status) as any),
    ),
    startsAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: "datetime" }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
    locations: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.typedUnion(
          [
            /*#__PURE__*/ l.typedRef<Uri>((() => uri) as any),
            /*#__PURE__*/ l.typedRef<LocationAddress.Main>(
              (() => LocationAddress.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationFsq.Main>(
              (() => LocationFsq.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationGeo.Main>(
              (() => LocationGeo.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationHthree.Main>(
              (() => LocationHthree.main) as any,
            ),
          ],
          false,
        ),
      ),
    ),
    description: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);

/** The mode of the event. */
type Mode =
  | "community.lexicon.calendar.event#hybrid"
  | "community.lexicon.calendar.event#inperson"
  | "community.lexicon.calendar.event#virtual"
  | l.UnknownString;

export type { Mode };

/** The mode of the event. */
const mode = /*#__PURE__*/ l.withDefault(
  /*#__PURE__*/ l.string<{
    knownValues: [
      "community.lexicon.calendar.event#hybrid",
      "community.lexicon.calendar.event#inperson",
      "community.lexicon.calendar.event#virtual",
    ];
  }>(),
  "community.lexicon.calendar.event#inperson",
);

export { mode };

/** A hybrid event that takes place both online and offline. */
const hybrid = /*#__PURE__*/ l.token($nsid, "hybrid");

export { hybrid };

/** A hybrid event that takes place both online and offline. */
const Hybrid = /*#__PURE__*/ hybrid.value;

/** A hybrid event that takes place both online and offline. */
type Hybrid = typeof Hybrid;

export { Hybrid };

/** The status of the event. */
type Status =
  | "community.lexicon.calendar.event#cancelled"
  | "community.lexicon.calendar.event#planned"
  | "community.lexicon.calendar.event#postponed"
  | "community.lexicon.calendar.event#rescheduled"
  | "community.lexicon.calendar.event#scheduled"
  | l.UnknownString;

export type { Status };

/** The status of the event. */
const status = /*#__PURE__*/ l.withDefault(
  /*#__PURE__*/ l.string<{
    knownValues: [
      "community.lexicon.calendar.event#cancelled",
      "community.lexicon.calendar.event#planned",
      "community.lexicon.calendar.event#postponed",
      "community.lexicon.calendar.event#rescheduled",
      "community.lexicon.calendar.event#scheduled",
    ];
  }>(),
  "community.lexicon.calendar.event#scheduled",
);

export { status };

/** The event has been created, but not finalized. */
const planned = /*#__PURE__*/ l.token($nsid, "planned");

export { planned };

/** The event has been created, but not finalized. */
const Planned = /*#__PURE__*/ planned.value;

/** The event has been created, but not finalized. */
type Planned = typeof Planned;

export { Planned };

/** A virtual event that takes place online. */
const virtual = /*#__PURE__*/ l.token($nsid, "virtual");

export { virtual };

/** A virtual event that takes place online. */
const Virtual = /*#__PURE__*/ virtual.value;

/** A virtual event that takes place online. */
type Virtual = typeof Virtual;

export { Virtual };

/** An in-person event that takes place offline. */
const inperson = /*#__PURE__*/ l.token($nsid, "inperson");

export { inperson };

/** An in-person event that takes place offline. */
const Inperson = /*#__PURE__*/ inperson.value;

/** An in-person event that takes place offline. */
type Inperson = typeof Inperson;

export { Inperson };

/** The event has been cancelled. */
const cancelled = /*#__PURE__*/ l.token($nsid, "cancelled");

export { cancelled };

/** The event has been cancelled. */
const Cancelled = /*#__PURE__*/ cancelled.value;

/** The event has been cancelled. */
type Cancelled = typeof Cancelled;

export { Cancelled };

/** The event has been postponed and a new start date has not been set. */
const postponed = /*#__PURE__*/ l.token($nsid, "postponed");

export { postponed };

/** The event has been postponed and a new start date has not been set. */
const Postponed = /*#__PURE__*/ postponed.value;

/** The event has been postponed and a new start date has not been set. */
type Postponed = typeof Postponed;

export { Postponed };

/** The event has been created and scheduled. */
const scheduled = /*#__PURE__*/ l.token($nsid, "scheduled");

export { scheduled };

/** The event has been created and scheduled. */
const Scheduled = /*#__PURE__*/ scheduled.value;

/** The event has been created and scheduled. */
type Scheduled = typeof Scheduled;

export { Scheduled };

/** The event has been rescheduled. */
const rescheduled = /*#__PURE__*/ l.token($nsid, "rescheduled");

export { rescheduled };

/** The event has been rescheduled. */
const Rescheduled = /*#__PURE__*/ rescheduled.value;

/** The event has been rescheduled. */
type Rescheduled = typeof Rescheduled;

export { Rescheduled };
