/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as RepoStrongRef from "../../../com/atproto/repo/strongRef.defs";

const $nsid = "community.lexicon.calendar.rsvp";

type $nsid = typeof $nsid;

export { $nsid };

/** An RSVP for an event. */
type Main = {
  $type: "community.lexicon.calendar.rsvp";
  status:
    | "community.lexicon.calendar.rsvp#interested"
    | "community.lexicon.calendar.rsvp#going"
    | "community.lexicon.calendar.rsvp#notgoing"
    | l.UnknownString;
  subject: RepoStrongRef.Main;
};

export type { Main };

/** An RSVP for an event. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    status: /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.string<{
        knownValues: [
          "community.lexicon.calendar.rsvp#interested",
          "community.lexicon.calendar.rsvp#going",
          "community.lexicon.calendar.rsvp#notgoing",
        ];
      }>(),
      "community.lexicon.calendar.rsvp#going",
    ),
    subject: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
/** Going to the event */
const going = /*#__PURE__*/ l.token($nsid, "going");

export { going };

/** Going to the event */
const Going = /*#__PURE__*/ going.value;

/** Going to the event */
type Going = typeof Going;

export { Going };

/** Not going to the event */
const notgoing = /*#__PURE__*/ l.token($nsid, "notgoing");

export { notgoing };

/** Not going to the event */
const Notgoing = /*#__PURE__*/ notgoing.value;

/** Not going to the event */
type Notgoing = typeof Notgoing;

export { Notgoing };

/** Interested in the event */
const interested = /*#__PURE__*/ l.token($nsid, "interested");

export { interested };

/** Interested in the event */
const Interested = /*#__PURE__*/ interested.value;

/** Interested in the event */
type Interested = typeof Interested;

export { Interested };
