/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as RepoStrongRef from "../../../com/atproto/repo/strongRef.defs";

const $nsid = "social.laundryroom.forum.reply";

type $nsid = typeof $nsid;

export { $nsid };

/** A reply to a social.laundryroom.forum.thread, authored by a member in their own repo in the same social.laundryroom.forum space as the thread. */
type Main = {
  $type: "social.laundryroom.forum.reply";

  /**
   * The social.laundryroom.forum.thread this reply belongs to.
   */
  thread: RepoStrongRef.Main;

  /**
   * The social.laundryroom.forum.reply this one answers, when it answers a reply rather than the thread itself.
   */
  parent?: RepoStrongRef.Main;

  /**
   * The reply, as plain text.
   */
  text: string;

  /**
   * Client-declared timestamp when the reply was written.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A reply to a social.laundryroom.forum.thread, authored by a member in their own repo in the same social.laundryroom.forum space as the thread. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    thread: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    parent: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    text: /*#__PURE__*/ l.string({
      minGraphemes: 1,
      maxGraphemes: 3000,
      maxLength: 30000,
    }),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
