/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "social.laundryroom.forum.thread";

type $nsid = typeof $nsid;

export { $nsid };

/** A discussion thread in a laundryroom group, authored by a member in their own repo in the group's social.laundryroom.forum space. */
type Main = {
  $type: "social.laundryroom.forum.thread";

  /**
   * Title of the thread.
   */
  title: string;

  /**
   * The opening post, as plain text.
   */
  text: string;

  /**
   * What the thread is about, when it is about a record: the AT-URI of a community.lexicon.calendar.event (a meetup) of the same group, as the event record in the group's calendar space (the canonical one, never its public mirror).
   */
  subject?: l.AtUriString;

  /**
   * Client-declared timestamp when the thread was started.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A discussion thread in a laundryroom group, authored by a member in their own repo in the group's social.laundryroom.forum space. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.string({
      minGraphemes: 1,
      maxGraphemes: 255,
      maxLength: 2550,
    }),
    text: /*#__PURE__*/ l.string({
      minGraphemes: 1,
      maxGraphemes: 3000,
      maxLength: 30000,
    }),
    subject: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: "at-uri" }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
