/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "social.laundryroom.authFull";

type $nsid = typeof $nsid;

export { $nsid };

/** Write access to the member's laundryroom profile, and to their own threads, replies, rsvps and pledges in the forum and calendar spaces (skey self) of any group. blob, account and community.lexicon.* repo permissions cannot be part of this set and are requested as raw scopes. */
const main = /*#__PURE__*/ l.permissionSet(
  $nsid,
  [
    /*#__PURE__*/ l.permission("repo", {
      collection: ["social.laundryroom.actor.profile"],
      action: ["create", "update", "delete"],
    }),
    /*#__PURE__*/ l.permission("space", {
      spaceType: "social.laundryroom.forum",
      authority: "*",
      skey: "self",
      collection: [
        "social.laundryroom.forum.thread",
        "social.laundryroom.forum.reply",
      ],
      action: ["create", "update", "delete"],
    }),
    /*#__PURE__*/ l.permission("space", {
      spaceType: "social.laundryroom.calendar",
      authority: "*",
      skey: "self",
      collection: [
        "community.lexicon.calendar.rsvp",
        "social.laundryroom.pledge.fulfillment",
      ],
      action: ["create", "update", "delete"],
    }),
  ],
  { title: "laundryroom", detail: "groups, meetups and rsvps on laundryroom" },
);

export { main };
