/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as RepoStrongRef from "../../../com/atproto/repo/strongRef.defs";

const $nsid = "social.laundryroom.calendar.attendance";

type $nsid = typeof $nsid;

export { $nsid };

/** The group's authoritative attendance outcome for a community.lexicon.calendar.event with a capacity: who got a place and who is on the waitlist, in order. Authored by the group in the event's calendar space. The rkey must equal the rkey of the event (a TID). */
type Main = {
  $type: "social.laundryroom.calendar.attendance";

  /**
   * The community.lexicon.calendar.event this outcome is for.
   */
  event: RepoStrongRef.Main;

  /**
   * DIDs of the members who have a place, in rsvp order. Absent means nobody.
   */
  going?: l.DidString[];

  /**
   * DIDs of the members waiting for a place, first in line first. Absent means nobody.
   */
  waitlist?: l.DidString[];

  /**
   * Client-declared timestamp when the record was created.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** The group's authoritative attendance outcome for a community.lexicon.calendar.event with a capacity: who got a place and who is on the waitlist, in order. Authored by the group in the event's calendar space. The rkey must equal the rkey of the event (a TID). */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    event: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    going: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: "did" }), {
        maxLength: 1000,
      }),
    ),
    waitlist: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: "did" }), {
        maxLength: 1000,
      }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
