/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as RepoStrongRef from "../../../com/atproto/repo/strongRef.defs";

const $nsid = "social.laundryroom.calendar.eventInfo";

type $nsid = typeof $nsid;

export { $nsid };

/** laundryroom-specific details of a community.lexicon.calendar.event, authored by the group next to the event in the same calendar space. The rkey must equal the rkey of the event (a TID), so there is one per event. */
type Main = {
  $type: "social.laundryroom.calendar.eventInfo";

  /**
   * The community.lexicon.calendar.event this record describes.
   */
  event: RepoStrongRef.Main;

  /**
   * Maximum number of attendees. Omitted when there is no limit; whether the event is full is derived, never stored. At most the number of places a social.laundryroom.calendar.attendance record can list.
   */
  capacity?: number;

  /**
   * The meetup's image.
   */
  image?: l.BlobRef;

  /**
   * Alt text for the image.
   */
  imageAlt?: string;

  /**
   * DID of the member who organizes the meetup.
   */
  organizer?: l.DidString;

  /**
   * Where the meetup happens, as free text. Kept here when the event carries no structured location.
   */
  locationText?: string;

  /**
   * Client-declared timestamp when the record was created.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** laundryroom-specific details of a community.lexicon.calendar.event, authored by the group next to the event in the same calendar space. The rkey must equal the rkey of the event (a TID), so there is one per event. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    event: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    capacity: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 1000 }),
    ),
    image: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({
        accept: ["image/png", "image/jpeg", "image/webp"],
        maxSize: 2000000,
      }),
    ),
    imageAlt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 1000, maxLength: 10000 }),
    ),
    organizer: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: "did" }),
    ),
    locationText: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 255, maxLength: 2550 }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
