/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "social.laundryroom.actor.profile";

type $nsid = typeof $nsid;

export { $nsid };

/** A person's laundryroom profile, in their public repo. Optional: apps fall back to app.bsky.actor.profile for the name and avatar. Everything in it is public. */
type Main = {
  $type: "social.laundryroom.actor.profile";

  /**
   * The name shown next to the person's posts and rsvps.
   */
  displayName?: string;

  /**
   * Free-form bio.
   */
  description?: string;

  /**
   * Free-form pronouns, as the person writes them.
   */
  pronouns?: string;

  /**
   * Links the person wants to show. Absolute http or https URLs; clients must check the scheme before rendering a link.
   */
  links?: l.UriString[];

  /**
   * Square avatar image.
   */
  avatar?: l.BlobRef;

  /**
   * Client-declared timestamp when the profile was first created. Kept on updates.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A person's laundryroom profile, in their public repo. Optional: apps fall back to app.bsky.actor.profile for the name and avatar. Everything in it is public. */
const main = /*#__PURE__*/ l.record<"literal:self", Main>(
  "literal:self",
  $nsid,
  /*#__PURE__*/ l.object({
    displayName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 64, maxLength: 640 }),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 2000, maxLength: 20000 }),
    ),
    pronouns: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 64, maxLength: 640 }),
    ),
    links: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.string({ format: "uri", maxLength: 2000 }),
        { maxLength: 10 },
      ),
    ),
    avatar: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({
        accept: ["image/png", "image/jpeg", "image/webp"],
        maxSize: 2000000,
      }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
