/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as RepoStrongRef from "../../../com/atproto/repo/strongRef.defs";

const $nsid = "social.laundryroom.pledge.board";

type $nsid = typeof $nsid;

export { $nsid };

/** A pledge board for a community.lexicon.calendar.event (things members can bring or do), authored by the group in the event's calendar space. The rkey must equal the rkey of the event (a TID), so there is at most one board per event. */
type Main = {
  $type: "social.laundryroom.pledge.board";

  /**
   * The community.lexicon.calendar.event the board belongs to.
   */
  event: RepoStrongRef.Main;

  /**
   * Title of the board.
   */
  title: string;

  /**
   * What the board is for.
   */
  description?: string;

  /**
   * Client-declared timestamp when the board was created.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A pledge board for a community.lexicon.calendar.event (things members can bring or do), authored by the group in the event's calendar space. The rkey must equal the rkey of the event (a TID), so there is at most one board per event. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    event: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    title: /*#__PURE__*/ l.string({
      minGraphemes: 1,
      maxGraphemes: 255,
      maxLength: 2550,
    }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 2000, maxLength: 20000 }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
