/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as RepoStrongRef from "../../../com/atproto/repo/strongRef.defs";

const $nsid = "social.laundryroom.pledge.fulfillment";

type $nsid = typeof $nsid;

export { $nsid };

/** A member's pledge to bring or do some of a social.laundryroom.pledge.item, authored by the member in their own repo in the item's calendar space. The rkey must equal the rkey of the item (a TID), so there is one per member and item. */
type Main = {
  $type: "social.laundryroom.pledge.fulfillment";

  /**
   * The social.laundryroom.pledge.item being pledged.
   */
  item: RepoStrongRef.Main;

  /**
   * How many the member pledges.
   */
  quantity: number;

  /**
   * Client-declared timestamp when the pledge was made.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A member's pledge to bring or do some of a social.laundryroom.pledge.item, authored by the member in their own repo in the item's calendar space. The rkey must equal the rkey of the item (a TID), so there is one per member and item. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    item: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    quantity: /*#__PURE__*/ l.integer({ minimum: 1 }),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
