/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as RepoStrongRef from "../../../com/atproto/repo/strongRef.defs";

const $nsid = "social.laundryroom.pledge.item";

type $nsid = typeof $nsid;

export { $nsid };

/** One thing on a social.laundryroom.pledge.board that members can pledge to bring or do, authored by the group in the board's calendar space. */
type Main = {
  $type: "social.laundryroom.pledge.item";

  /**
   * The social.laundryroom.pledge.board this item is on.
   */
  board: RepoStrongRef.Main;

  /**
   * What is needed.
   */
  title: string;

  /**
   * Details about the item.
   */
  description?: string;

  /**
   * How many are needed in total, summed over the quantities of all fulfillments. Omitted when there is no limit.
   */
  capacity?: number;

  /**
   * Position on the board, ascending.
   */
  sortOrder?: number;

  /**
   * Client-declared timestamp when the item was created.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** One thing on a social.laundryroom.pledge.board that members can pledge to bring or do, authored by the group in the board's calendar space. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    board: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    title: /*#__PURE__*/ l.string({
      minGraphemes: 1,
      maxGraphemes: 255,
      maxLength: 2550,
    }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 2000, maxLength: 20000 }),
    ),
    capacity: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer({ minimum: 1 })),
    sortOrder: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.integer({ minimum: 0 }), 0),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
